"""create teams and players tables

Revision ID: 3db47e468d67
Revises: 
Create Date: 2026-09-24 23:06:12.646233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db47e468d67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('founded_date', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('titles_won', sa.Integer(), nullable=False),
    sa.Column('uefa_ranking', sa.Integer(), nullable=False),
    sa.Column('division', sa.Enum('first', 'second', 'third', name='teamdivision'), nullable=False),
    sa.Column('head_coach', sa.String(length=100), nullable=False),
    sa.Column('president', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_country'), 'teams', ['country'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('performance', sa.Integer(), nullable=False),
    sa.Column('field_position', sa.Enum('goalkeeper', 'defender', 'midfielder', 'forward', name='playerposition'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_country'), 'players', ['country'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_country'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_country'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
